apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  name: nfs-a
  namespace: rook-ceph
spec:
  rados:
    pool: nfs-ganesha
    namespace: nfs-ns
  server:
    active: 2
    placement:
      all: false
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - worker-node-1
                    - worker-node-2
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
